"""empty message

Revision ID: c67d4daa6dd6
Revises: 59df671f5438
Create Date: 2019-03-07 04:04:14.013102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c67d4daa6dd6'
down_revision = '59df671f5438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('transactions', 't_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 't_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
